artisan 'cache:clear' is breaking Mockery in php 8.0.2
ErrorException: Method ReflectionParameter::isArray() is deprecated

/home/runner/work/laravel-query-cache/laravel-query-cache/vendor/mockery/mockery/library/Mockery/Generator/Parameter.php:58
/home/runner/work/laravel-query-cache/laravel-query-cache/vendor/mockery/mockery/library/Mockery/Generator/StringManipulation/Pass/MethodDefinitionPass.php:104
/home/runner/work/laravel-query-cache/laravel-query-cache/vendor/mockery/mockery/library/Mockery/Generator/StringManipulation/Pass/MethodDefinitionPass.php:71
/home/runner/work/laravel-query-cache/laravel-query-cache/vendor/mockery/mockery/library/Mockery/Generator/StringManipulation/Pass/MethodDefinitionPass.php:47
/home/runner/work/laravel-query-cache/laravel-query-cache/vendor/mockery/mockery/library/Mockery/Generator/StringManipulationGenerator.php:79
/home/runner/work/laravel-query-cache/laravel-query-cache/vendor/mockery/mockery/library/Mockery/Generator/CachingGenerator.php:40
/home/runner/work/laravel-query-cache/laravel-query-cache/vendor/mockery/mockery/library/Mockery/Container.php:221
/home/runner/work/laravel-query-cache/laravel-query-cache/vendor/mockery/mockery/library/Mockery.php:118
/home/runner/work/laravel-query-cache/laravel-query-cache/vendor/laravel/framework/src/Illuminate/Testing/PendingCommand.php:286
/home/runner/work/laravel-query-cache/laravel-query-cache/vendor/laravel/framework/src/Illuminate/Testing/PendingCommand.php:251
/home/runner/work/laravel-query-cache/laravel-query-cache/vendor/laravel/framework/src/Illuminate/Testing/PendingCommand.php:191
/home/runner/work/laravel-query-cache/laravel-query-cache/vendor/laravel/framework/src/Illuminate/Testing/PendingCommand.php:346
/home/runner/work/laravel-query-cache/laravel-query-cache/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithConsole.php:59
/home/runner/work/laravel-query-cache/laravel-query-cache/tests/TestCase.php:53
/home/runner/work/laravel-query-cache/laravel-query-cache/tests/TestCase.php:15